version: "3"
services:
  mysql:
    container_name: mysql
    ports:
      - 3306:3306
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
    restart: always
    command: [
            '--default-authentication-plugin=mysql_native_password',
            '--default-time-zone=+8:00'
    ]        
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos